service: api-dynamodb-service
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-2
  memorySize: 128
  environment:
    DYNAMODB_TABLE:
      "Fn::ImportValue": "vehicle-table-${self:provider.stage}"

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/vehicle-table-${self:provider.stage}"

functions:
  createVehicle:
    handler: src/handlers/createVehicle.main
    events:
      - http:
          path: vehicle
          method: post
          cors: true
  getVehicles:
    handler: src/handlers/getVehicles.main
    events:
      - http:
          path: vehicles
          method: get
          cors: true
  getVehicle:
    handler: src/handlers/getVehicle.main
    events:
      - http:
          path: vehicle/{id}
          method: get
          cors: true
  deleteVehicle:
    handler: src/handlers/deleteVehicle.main
    events:
      - http:
          path: vehicle/{id}
          method: delete
          cors: true
  updateVehicle:
    handler: src/handlers/updateVehicle.main
    events:
      - http:
          path: vehicle/{id}
          method: put
          cors: true
