service: s3-file-processor
frameworkVersion: "2"

custom:
  bucket: ruslan-gederin-odessa-for-lambda

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-2
  memorySize: 128
  environment:
    QUEUE_URL: { Ref: S3Queue }
    REGION: ${self:provider.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:GetObject"
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"
    - Effect: Allow
      Action:
        - "sqs:SendMessage"
      Resource: arn:aws:sqs:*:*:S3Queue

functions:
  process-s3-to-sqs:
    handler: src/handler.s3processor
    events:
      - s3: ${self:custom.bucket}

resources:
  Resources:
    S3Queue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "S3Queue"
